-- Migration: audit trail enrichment (audit-remediation task 4.1)
-- Adds previous/new value capture, reason, and correlation id to activity_log.
-- correlation_id links all trail rows generated by one request/document flow.

ALTER TABLE activity_log ADD COLUMN old_value TEXT;
ALTER TABLE activity_log ADD COLUMN new_value TEXT;
ALTER TABLE activity_log ADD COLUMN reason TEXT;
ALTER TABLE activity_log ADD COLUMN correlation_id TEXT;

CREATE INDEX IF NOT EXISTS idx_activity_log_correlation ON activity_log(correlation_id) WHERE correlation_id IS NOT NULL;
